# Proyecto Riesgos en Entidades Financieras
## Estudiantes: Ingrid Fonseca, Jimena Chacón, María José Bolaños y Sofía Sequeira

## Librerías

In [12]:
import yfinance as yf
import pandas as pd
import numpy as np

### Precios históricos de las acciones

In [13]:
# Lista de ISIN y fechas de adquisición
isin_data = {
    'US30303M1027': '2021-12-29',
    'US8969452015': '2021-12-28',
    'ES0177542018': '2021-12-29',
    'IT0003128367': '2021-12-30',
    'ES0130960018': '2021-12-30',
    'ES0130670112': '2022-01-04',
    'US2546871060': '2022-02-10'
}

In [14]:
# ISIN mapping to ticker symbols for yfinance
isin_to_ticker = {
    'US30303M1027': 'META',
    'US8969452015': 'TRIP',
    'ES0177542018': 'IAG.L',
    'IT0003128367': 'ENEL.MI',
    'ES0130960018': 'ENG.MC',
    'ES0130670112': 'ELE.MC',
    'US2546871060': 'DIS'
}

In [15]:
# Monedas de los tickers
isin_to_currency = {
    'US30303M1027': 'USD',
    'US8969452015': 'USD',
    'ES0177542018': 'EUR',
    'IT0003128367': 'EUR',
    'ES0130960018': 'EUR',
    'ES0130670112': 'EUR',
    'US2546871060': 'USD'
}

In [16]:
start_date = max(isin_data.values())

In [17]:
# Descargar datos de precios desde Yahoo Finance
precio_historico_usd = {}
precio_historico_eur = {}

for isin, fecha in isin_data.items():
    ticker = isin_to_ticker[isin]
    try:
        data = yf.download(ticker, start=start_date, end='2024-08-01')
        if not data.empty:
            if isin_to_currency[isin] == 'USD':
                precio_historico_usd[ticker] = data['Adj Close']  # Precios ajustados en USD
            elif isin_to_currency[isin] == 'EUR':
                precio_historico_eur[ticker] = data['Adj Close']  # Precios ajustados en EUR
        else:
            print(f"No se encontraron datos para {ticker}")
    except Exception as e:
        print(f"Error al descargar datos para {ticker}: {e}")


[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [18]:
precio_usd_df = pd.concat(precio_historico_usd, axis=1)
precio_usd_df.columns = precio_historico_usd.keys()
precio_usd_df

META       TRIP         DIS
Date                                         
2022-02-10  227.385376  29.340000  150.969223
2022-02-11  218.890945  28.610001  148.300262
2022-02-14  217.046494  28.370001  149.669479
2022-02-15  220.336594  30.070000  153.509186
2022-02-16  215.889969  29.230000  155.126434
...                ...        ...         ...
2024-07-25  452.977875  17.610001   89.209999
2024-07-26  465.256165  17.900000   89.930000
2024-07-29  465.266144  17.969999   92.139999
2024-07-30  462.748535  18.020000   93.790001
2024-07-31  474.377441  17.629999   93.690002

[620 rows x 3 columns]

In [19]:
precio_eur_df = pd.concat(precio_historico_eur, axis=1)
precio_eur_df.columns = precio_historico_eur.keys()
precio_eur_df

IAG.L   ENEL.MI     ENG.MC     ELE.MC
Date                                                  
2022-02-10  175.426514  5.415340  14.436002  15.766635
2022-02-11  171.825500  5.383347  14.416932  15.649594
2022-02-14  162.144089  5.321043  14.188091  15.323563
2022-02-15  169.621597  5.412814  14.146138  15.490759
2022-02-16  170.585815  5.481011  14.165209  15.574358
...                ...       ...        ...        ...
2024-07-25  162.193283  6.660000  13.670000  18.040001
2024-07-26  164.456207  6.670000  13.620000  18.025000
2024-07-29  161.406174  6.650000  13.650000  18.020000
2024-07-30  162.734406  6.630000  13.710000  18.014999
2024-07-31  163.127960  6.594000  13.840000  17.900000

[634 rows x 4 columns]

In [20]:
precio_eur_df = precio_eur_df.reset_index()

### Tipos de cambio

Fuente: Banco Central de Costa Rica

Periodo: 10/02/2022 a 31/07/2024

In [21]:
tc_euro_dolar=pd.read_excel('tc_euro_dolar.xlsx')
tc_euro_dolar

Fecha      TC  Mes   Año
0    10 Feb  1.1405    2  2022
1    11 Feb  1.1393    2  2022
2    14 Feb  1.1314    2  2022
3    15 Feb  1.1355    2  2022
4    16 Feb  1.1358    2  2022
..      ...     ...  ...   ...
629  25 Jul  1.0837    7  2024
630  26 Jul  1.0856    7  2024
631  29 Jul  1.0812    7  2024
632  30 Jul  1.0810    7  2024
633  31 Jul  1.0843    7  2024

[634 rows x 4 columns]

In [22]:
tc_dolar_colon=pd.read_excel("tc_dolar_colon.xlsx")
tc_dolar_colon

Fecha      TC  Mes   Año
0    10 Feb 2022  641.03    2  2022
1    11 Feb 2022  640.19    2  2022
2    14 Feb 2022  638.63    2  2022
3    15 Feb 2022  636.03    2  2022
4    16 Feb 2022  636.35    2  2022
..           ...     ...  ...   ...
610  25 Jul 2024  522.41    7  2024
611  26 Jul 2024  522.41    7  2024
612  29 Jul 2024  523.18    7  2024
613  30 Jul 2024  522.02    7  2024
614  31 Jul 2024  521.33    7  2024

[615 rows x 4 columns]

In [23]:
tc1= tc_dolar_colon[['TC','Año','Mes']]
desv=tc1.groupby(['Año', 'Mes']).std()
desv=desv.rename(columns={'TC': 'std_mensual'})
tc_dolar_colon = tc_dolar_colon.merge(desv, on=['Año', 'Mes'])
tc_dolar_colon

Fecha      TC  Mes   Año  std_mensual
0    10 Feb 2022  641.03    2  2022     1.584601
1    11 Feb 2022  640.19    2  2022     1.584601
2    14 Feb 2022  638.63    2  2022     1.584601
3    15 Feb 2022  636.03    2  2022     1.584601
4    16 Feb 2022  636.35    2  2022     1.584601
..           ...     ...  ...   ...          ...
610  25 Jul 2024  522.41    7  2024     2.566257
611  26 Jul 2024  522.41    7  2024     2.566257
612  29 Jul 2024  523.18    7  2024     2.566257
613  30 Jul 2024  522.02    7  2024     2.566257
614  31 Jul 2024  521.33    7  2024     2.566257

[615 rows x 5 columns]

In [24]:
#Creación de los escenarios
tc_dolar_colon['Optimista']=tc_dolar_colon['TC']+2*tc_dolar_colon['std_mensual']
tc_dolar_colon['Pesimista']=tc_dolar_colon['TC']-2*tc_dolar_colon['std_mensual']

In [25]:
tc_dolar_colon

Fecha      TC  Mes   Año  std_mensual   Optimista   Pesimista
0    10 Feb 2022  641.03    2  2022     1.584601  644.199203  637.860797
1    11 Feb 2022  640.19    2  2022     1.584601  643.359203  637.020797
2    14 Feb 2022  638.63    2  2022     1.584601  641.799203  635.460797
3    15 Feb 2022  636.03    2  2022     1.584601  639.199203  632.860797
4    16 Feb 2022  636.35    2  2022     1.584601  639.519203  633.180797
..           ...     ...  ...   ...          ...         ...         ...
610  25 Jul 2024  522.41    7  2024     2.566257  527.542514  517.277486
611  26 Jul 2024  522.41    7  2024     2.566257  527.542514  517.277486
612  29 Jul 2024  523.18    7  2024     2.566257  528.312514  518.047486
613  30 Jul 2024  522.02    7  2024     2.566257  527.152514  516.887486
614  31 Jul 2024  521.33    7  2024     2.566257  526.462514  516.197486

[615 rows x 7 columns]

### Dolarización de las acciones Europeas

In [26]:
tc_eur=tc_euro_dolar['TC']
precios0=precio_eur_df[['IAG.L','ENEL.MI','ENG.MC','ELE.MC']]
precios_eur_dolar= precios0.mul(tc_eur, axis=0)
precios_eur_dolar['Date']=precio_eur_df[['Date']]
precios_eur_dolar

IAG.L   ENEL.MI     ENG.MC     ELE.MC       Date
0    200.073939  6.176196  16.464260  17.981847 2022-02-10
1    195.760793  6.133247  16.425211  17.829583 2022-02-11
2    183.449822  6.020228  16.052406  17.337079 2022-02-14
3    192.605324  6.146250  16.062940  17.589757 2022-02-15
4    193.751369  6.225333  16.088844  17.689356 2022-02-16
..          ...       ...        ...        ...        ...
629  175.768861  7.217442  14.814179  19.549949 2024-07-25
630  178.533659  7.240952  14.785872  19.567940 2024-07-26
631  174.512355  7.189980  14.758380  19.483224 2024-07-29
632  175.915892  7.167030  14.820510  19.474214 2024-07-30
633  176.879647  7.149874  15.006712  19.408970 2024-07-31

[634 rows x 5 columns]

In [27]:
precios_dolar=pd.merge(precio_usd_df, precios_eur_dolar, on='Date', how='inner')
precios_dolar

Date        META       TRIP         DIS       IAG.L   ENEL.MI  \
0   2022-02-10  227.385376  29.340000  150.969223  200.073939  6.176196   
1   2022-02-11  218.890945  28.610001  148.300262  195.760793  6.133247   
2   2022-02-14  217.046494  28.370001  149.669479  183.449822  6.020228   
3   2022-02-15  220.336594  30.070000  153.509186  192.605324  6.146250   
4   2022-02-16  215.889969  29.230000  155.126434  193.751369  6.225333   
..         ...         ...        ...         ...         ...       ...   
610 2024-07-25  452.977875  17.610001   89.209999  175.768861  7.217442   
611 2024-07-26  465.256165  17.900000   89.930000  178.533659  7.240952   
612 2024-07-29  465.266144  17.969999   92.139999  174.512355  7.189980   
613 2024-07-30  462.748535  18.020000   93.790001  175.915892  7.167030   
614 2024-07-31  474.377441  17.629999   93.690002  176.879647  7.149874   

        ENG.MC     ELE.MC  
0    16.464260  17.981847  
1    16.425211  17.829583  
2    16.052406  17.337079  
3    16.062940  17.589757  
4    16.088844  17.689356  
..         ...        ...  
610  14.814179  19.549949  
611  14.785872  19.567940  
612  14.758380  19.483224  
613  14.820510  19.474214  
614  15.006712  19.408970  

[615 rows x 8 columns]

### Colonización de las acciones

#### Escenario Base

In [28]:
tc1=tc_dolar_colon['TC']
precios1=precios_dolar[['META','TRIP','DIS','IAG.L','ENEL.MI','ENG.MC','ELE.MC']]
cartera_base = precios1.mul(tc1, axis=0)
cartera_base

META          TRIP           DIS          IAG.L      ENEL.MI  \
0    145760.847562  18807.820298  96775.801034  128253.397016  3959.126764   
1    140131.794358  18315.836291  94940.345019  125324.101883  3926.443574   
2    138612.402163  18117.933636  95583.419610  117156.559828  3844.698250   
3    140140.683645  19125.421906  97636.447439  122502.764047  3909.199678   
4    137381.581692  18600.510209  98714.706483  123293.683768  3961.490488   
..             ...           ...           ...            ...          ...   
610  236640.171551   9199.640419  46604.195622   91823.410610  3770.463789   
611  243054.472923   9351.138801  46980.331459   93267.768599  3782.745778   
612  243417.941113   9401.544241  48205.804881   91301.373895  3761.653790   
613  241563.990322   9406.800639  48960.256278   91831.614132  3741.333065   
614  247307.191528   9191.047462  48843.408973   92212.666501  3727.443839   

           ENG.MC        ELE.MC  
0    10554.084605  11526.903479  
1    10515.255669  11414.320609  
2    10251.548345  11071.978603  
3    10216.511675  11187.612971  
4    10238.135990  11256.621564  
..            ...           ...  
610   7739.075295  10213.088853  
611   7724.287327  10222.487319  
612   7721.289033  10193.233391  
613   7736.602652  10165.929370  
614   7823.449253  10118.478114  

[615 rows x 7 columns]

#### Escenario Optimista

In [29]:
tc2=tc_dolar_colon['Optimista']
cartera_opt = precios1.mul(tc2, axis=0)
cartera_opt

META          TRIP           DIS          IAG.L      ENEL.MI  \
0    146481.477964  18900.804713  97254.253139  128887.471932  3978.700381   
1    140825.504185  18406.507189  95410.338646  125944.507562  3945.881079   
2    139300.266549  18207.843926  96057.752564  117737.949543  3863.777575   
3    140838.975025  19220.719837  98122.949202  123113.169406  3928.678393   
4    138065.780816  18693.146009  99206.333635  123907.721177  3981.219830   
..             ...           ...           ...            ...          ...   
610  238965.086894   9290.023996  47062.067203   92725.546772  3807.507411   
611  245442.406762   9443.010802  47441.898457   94184.095124  3819.910066   
612  245805.926170   9493.775516  48678.714730   92197.061023  3798.556465   
613  243939.053718   9499.288546  49441.634783   92734.504935  3778.117949   
614  249741.940449   9281.533682  49324.274234   93120.503790  3764.140669   

           ENG.MC        ELE.MC  
0    10606.263187  11583.891602  
1    10567.310495  11470.826175  
2    10302.421679  11126.923323  
3    10267.418391  11243.358479  
4    10289.124802  11312.682722  
..            ...           ...  
610   7815.109278  10313.429242  
611   7800.176023  10322.920045  
612   7797.036624  10293.231316  
613   7812.669129  10265.881050  
614   7900.471415  10218.094925  

[615 rows x 7 columns]

#### Escenario Pesimista

In [30]:
tc3=tc_dolar_colon['Pesimista']
cartera_pes = precios1.mul(tc3, axis=0)
cartera_pes

META          TRIP           DIS          IAG.L      ENEL.MI  \
0    145040.217160  18714.835883  96297.348929  127619.322101  3939.553146   
1    139438.084530  18225.165393  94470.351391  124703.696203  3907.006069   
2    137924.537778  18028.023346  95109.086656  116575.170113  3825.618926   
3    139442.392265  19030.123974  97149.945676  121892.358689  3889.720963   
4    136697.382568  18507.874408  98223.079332  122679.646359  3941.761145   
..             ...           ...           ...            ...          ...   
610  234315.256208   9109.256842  46146.324041   90921.274448  3733.420167   
611  240666.539084   9259.266800  46518.764462   92351.442073  3745.581489   
612  241029.956055   9309.312965  47732.895032   90405.686767  3724.751116   
613  239188.926927   9314.312732  48478.877773   90928.723329  3704.548182   
614  244872.442607   9100.561243  48362.543711   91304.829212  3690.747009   

           ENG.MC        ELE.MC  
0    10501.906024  11469.915356  
1    10463.200843  11357.815043  
2    10200.675011  11017.033882  
3    10165.604958  11131.867462  
4    10187.147178  11200.560406  
..            ...           ...  
610   7663.041311  10112.748464  
611   7648.398630  10122.054593  
612   7645.541441  10093.235466  
613   7660.536175  10065.977690  
614   7746.427091  10018.861304  

[615 rows x 7 columns]

# Riesgo de precio

#### Escenario Base

In [31]:
rendimientos = np.log(cartera_base / cartera_base.shift(1)).dropna()
rendimientos

META      TRIP       DIS     IAG.L   ENEL.MI    ENG.MC    ELE.MC
1   -0.039384 -0.026507 -0.019148 -0.023105 -0.008289 -0.003686 -0.009815
2   -0.010902 -0.010864  0.006751 -0.067392 -0.021039 -0.025398 -0.030451
3    0.010965  0.054116  0.021251  0.044622  0.016638 -0.003424  0.010390
4   -0.019884 -0.027829  0.010983  0.006436  0.013288  0.002114  0.006149
5   -0.040611 -0.024271 -0.020965 -0.040319 -0.002937 -0.005652  0.008860
..        ...       ...       ...       ...       ...       ...       ...
610 -0.019080  0.008381 -0.008485  0.005986  0.000903  0.000938 -0.000685
611  0.026745  0.016334  0.008038  0.015607  0.003252 -0.001913  0.000920
612  0.001494  0.005376  0.025750 -0.021309 -0.005591 -0.000388 -0.002866
613 -0.007645  0.000559  0.015529  0.005791 -0.005417  0.001981 -0.002682
614  0.023497 -0.023203 -0.002389  0.004141 -0.003719  0.011163 -0.004679

[583 rows x 7 columns]

#### Escenario Optimista

In [32]:
rendimientos_opt = np.log(cartera_opt / cartera_opt.shift(1)).dropna()
rendimientos_opt

META      TRIP       DIS     IAG.L   ENEL.MI    ENG.MC    ELE.MC
1   -0.039377 -0.026500 -0.019142 -0.023098 -0.008283 -0.003679 -0.009809
2   -0.010890 -0.010852  0.006763 -0.067380 -0.021027 -0.025386 -0.030439
3    0.010985  0.054136  0.021272  0.044643  0.016658 -0.003403  0.010410
4   -0.019887 -0.027832  0.010981  0.006433  0.013285  0.002112  0.006147
5   -0.040616 -0.024276 -0.020970 -0.040324 -0.002942 -0.005657  0.008855
..        ...       ...       ...       ...       ...       ...       ...
610 -0.019062  0.008399 -0.008467  0.006005  0.000921  0.000957 -0.000667
611  0.026745  0.016334  0.008038  0.015607  0.003252 -0.001913  0.000920
612  0.001480  0.005362  0.025736 -0.021323 -0.005606 -0.000403 -0.002880
613 -0.007624  0.000581  0.015551  0.005812 -0.005395  0.002003 -0.002661
614  0.023510 -0.023190 -0.002377  0.004154 -0.003706  0.011176 -0.004666

[583 rows x 7 columns]

#### Escenario pesimista

In [33]:
rendimientos_pes = np.log(cartera_pes / cartera_pes.shift(1)).dropna()
rendimientos_pes

META      TRIP       DIS     IAG.L   ENEL.MI    ENG.MC    ELE.MC
1   -0.039390 -0.026513 -0.019155 -0.023111 -0.008296 -0.003692 -0.009821
2   -0.010914 -0.010876  0.006738 -0.067404 -0.021051 -0.025411 -0.030463
3    0.010945  0.054096  0.021231  0.044602  0.016617 -0.003444  0.010369
4   -0.019882 -0.027827  0.010986  0.006438  0.013290  0.002117  0.006152
5   -0.040606 -0.024265 -0.020960 -0.040314 -0.002932 -0.005647  0.008865
..        ...       ...       ...       ...       ...       ...       ...
610 -0.019099  0.008362 -0.008504  0.005967  0.000884  0.000919 -0.000704
611  0.026745  0.016334  0.008038  0.015607  0.003252 -0.001913  0.000920
612  0.001509  0.005390  0.025765 -0.021294 -0.005577 -0.000374 -0.002851
613 -0.007667  0.000537  0.015507  0.005769 -0.005439  0.001959 -0.002704
614  0.023484 -0.023216 -0.002403  0.004128 -0.003732  0.011150 -0.004692

[583 rows x 7 columns]

ACP

In [34]:
cartera_oceanica = pd.read_excel("Inversiones -07-2024     Oficial Riesgos F.xlsx")

In [35]:
acciones = cartera_oceanica[cartera_oceanica['[E] CodTitulo'] == 'AC'].reset_index()
acciones

index [E]CodReferencia   [E] CodISIN [E]Ramo [E] CodTitulo [E] NemoEmisor  \
0      4     A13000000121  US30303M1027     G10            AC             FB   
1      5     A13000000122  US8969452015     G06            AC           TRIP   
2      6     A13000000124  ES0177542018     G10            AC           ICAG   
3      7     A13000000125  IT0003128367     G06            AC           ENEI   
4      8     A13000000126  ES0130960018     G06            AC           ENAG   
5     10     A13000000129  ES0130670112     G06            AC            ELE   
6     11     A13000000130  ES0177542018     G10            AC           ICAG   
7     12     A13000000131  US2546871060     G01            AC           WALT   

  [E]NemotInstrumento [E] FecAdquisicion [E] FecVencimiento [A] CodMoneda  \
0                 afb         2021-12-29                NaT           USD   
1               atrip         2021-12-28                NaT           USD   
2               aicag         2021-12-29                NaT           EUR   
3               aenei         2021-12-30                NaT           EUR   
4               aenag         2021-12-30                NaT           EUR   
5                aele         2022-01-04                NaT           EUR   
6               aicag         2022-01-11                NaT           EUR   
7               awalt         2022-02-10                NaT           USD   

   ...  [E]Calificadora  [E]PlazoCalificacion [E]RiesgoEmisor  \
0  ...               MO                    LP              A1   
1  ...               SP                    LP             BB-   
2  ...               SP                    LP              BB   
3  ...               SP                    LP            BBB+   
4  ...               SP                    LP             BBB   
5  ...               SP                    LP            BBB+   
6  ...               SP                    LP              BB   
7  ...               SP                    LP            BBB+   

   [E]RiesgoCreditoEmision  [E]CodCustodio  [E]NumCustodia  \
0                      NaN          COTROS         14906.0   
1                      NaN          COTROS         14906.0   
2                      NaN          COTROS         14906.0   
3                      NaN          COTROS         14906.0   
4                      NaN          COTROS         14906.0   
5                      NaN          COTROS         14906.0   
6                      NaN          COTROS         14906.0   
7                      NaN          COTROS         14906.0   

   [E]ValorLibrosMonedaOriginal  [E]ValorLibrosColones  [E]Deterioro  \
0                           NaN                    NaN           NaN   
1                           NaN                    NaN           NaN   
2                           NaN                    NaN           NaN   
3                           NaN                    NaN           NaN   
4                           NaN                    NaN           NaN   
5                           NaN                    NaN           NaN   
6                           NaN                    NaN           NaN   
7                           NaN                    NaN           NaN   

   [E]CodTipoValoracion  
0                    RI  
1                    RI  
2                    RI  
3                    RI  
4                    RI  
5                    RI  
6                    RI  
7                    RI  

[8 rows x 34 columns]

In [36]:
montos = acciones['[E] CostoAdquisicion']
montos_numericos = pd.to_numeric(montos, errors='coerce')
vector_montos = np.array(montos_numericos)

In [37]:
vector_ordenado = np.array([vector_montos[0],vector_montos[1],vector_montos[6],vector_montos[3],vector_montos[2],vector_montos[4],vector_montos[5]])
vector_ordenado

array([27427800.5739    , 26592340.6911    , 56711705.49739191,
       28435381.4957058 , 29645089.16746545, 23822222.17386501,
       29137830.60257182])

In [38]:
import yfinance as yf
from datetime import datetime, timedelta

# Lista para almacenar los precios ajustados iniciales
precios_iniciales = []

for isin, fecha in isin_data.items():
    ticker = isin_to_ticker[isin]

    # Convertir la fecha a datetime
    fecha_dt = datetime.strptime(fecha, "%Y-%m-%d")

    # Sumar un día para obtener la fecha de fin
    fechas_iniciales = fecha_dt + timedelta(days=1)

    try:
        # Descargar datos desde Yahoo Finance
        data = yf.download(ticker, start=fecha_dt, end=fechas_iniciales)

        # Verificar si se obtuvo algún dato
        if not data.empty:
            precio_ajustado = data['Adj Close'].iloc[0]
            precios_iniciales.append(precio_ajustado)
        else:
            print(f"No se encontraron datos para {ticker} en {fecha}")

    except Exception as e:
        print(f"Error al descargar datos para {ticker}: {e}")

# Imprimir la lista de precios iniciales
precios_iniciales

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


[Ticker
 META    341.910583
 Name: 2021-12-29 00:00:00, dtype: float64,
 Ticker
 TRIP    27.370001
 Name: 2021-12-28 00:00:00, dtype: float64,
 Ticker
 IAG.L    141.147995
 Name: 2021-12-29 00:00:00, dtype: float64,
 Ticker
 ENEL.MI    5.769054
 Name: 2021-12-30 00:00:00, dtype: float64,
 Ticker
 ENG.MC    15.561133
 Name: 2021-12-30 00:00:00, dtype: float64,
 Ticker
 ELE.MC    16.92029
 Name: 2022-01-04 00:00:00, dtype: float64,
 Ticker
 DIS    150.969223
 Name: 2022-02-10 00:00:00, dtype: float64]

In [39]:
precios_iniciales_df = pd.concat(precios_iniciales, axis=0)
precios_iniciales_df

Ticker
META       341.910583
TRIP        27.370001
IAG.L      141.147995
ENEL.MI      5.769054
ENG.MC      15.561133
ELE.MC      16.920290
DIS        150.969223
dtype: float64

In [40]:
numero_acciones = vector_ordenado / precios_iniciales_df.values
numero_acciones = np.round(numero_acciones)
numero_acciones

array([  80219.,  971587.,  401789., 4928950., 1905073., 1407909.,
        193005.])

In [41]:
import yfinance as yf
from datetime import datetime, timedelta

# Lista para almacenar los precios ajustados iniciales
precios_finales = []

for isin, fecha in isin_data.items():
    ticker = isin_to_ticker[isin]

    try:
        # Descargar datos desde Yahoo Finance
        data = yf.download(ticker, start='2024-07-31', end='2024-08-01')

        # Verificar si se obtuvo algún dato
        if not data.empty:
            precio_ajustado = data['Adj Close'].iloc[0]
            precios_finales.append(precio_ajustado)
        else:
            print(f"No se encontraron datos para {ticker} en {fecha}")

    except Exception as e:
        print(f"Error al descargar datos para {ticker}: {e}")

# Imprimir la lista de precios iniciales
precios_finales

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


[Ticker
 META    474.377441
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 TRIP    17.629999
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 IAG.L    163.12796
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 ENEL.MI    6.594
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 ENG.MC    13.84
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 ELE.MC    17.9
 Name: 2024-07-31 00:00:00, dtype: float64,
 Ticker
 DIS    93.690002
 Name: 2024-07-31 00:00:00, dtype: float64]

In [42]:
precios_finales_df = pd.concat(precios_finales, axis=0)
precios_finales_df

Ticker
META       474.377441
TRIP        17.629999
IAG.L      163.127960
ENEL.MI      6.594000
ENG.MC      13.840000
ELE.MC      17.900000
DIS         93.690002
Name: 2024-07-31 00:00:00, dtype: float64

In [43]:
precios_finales_df

Ticker
META       474.377441
TRIP        17.629999
IAG.L      163.127960
ENEL.MI      6.594000
ENG.MC      13.840000
ELE.MC      17.900000
DIS         93.690002
Name: 2024-07-31 00:00:00, dtype: float64

In [44]:
valor_de_cartera = numero_acciones* precios_finales_df
valor_de_cartera

Ticker
META       3.805408e+07
TRIP       1.712908e+07
IAG.L      6.554302e+07
ENEL.MI    3.250150e+07
ENG.MC     2.636621e+07
ELE.MC     2.520157e+07
DIS        1.808264e+07
Name: 2024-07-31 00:00:00, dtype: float64

In [45]:
Lastday_tc_euro_dolar = tc_euro_dolar['TC'][633]
Lastday_tc_euro_dolar

1.0843

In [46]:
Lastday_tc_dolar_colon = tc_dolar_colon['TC'][614]
Lastday_tc_dolar_colon

521.33

In [47]:
valor_de_cartera_dolares = np.array([valor_de_cartera[0],valor_de_cartera[1],valor_de_cartera[2]*Lastday_tc_euro_dolar,valor_de_cartera[3]*Lastday_tc_euro_dolar,valor_de_cartera[4]*Lastday_tc_euro_dolar,valor_de_cartera[5]*Lastday_tc_euro_dolar,valor_de_cartera[6]])
valor_de_cartera_dolares

<ipython-input-47-74475f4a681b>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  valor_de_cartera_dolares = np.array([valor_de_cartera[0],valor_de_cartera[1],valor_de_cartera[2]*Lastday_tc_euro_dolar,valor_de_cartera[3]*Lastday_tc_euro_dolar,valor_de_cartera[4]*Lastday_tc_euro_dolar,valor_de_cartera[5]*Lastday_tc_euro_dolar,valor_de_cartera[6]])


array([38054083.97216797, 17129077.99461174, 71068296.5890774 ,
       35241371.70414004, 28588882.16517233, 27326062.96137995,
       18082638.92120361])

In [48]:
valor_de_cartera_colones = valor_de_cartera_dolares*Lastday_tc_dolar_colon
valor_de_cartera_colones

array([1.98387356e+10, 8.92990223e+09, 3.70500351e+10, 1.83723843e+10,
       1.49042419e+10, 1.42458964e+10, 9.42702215e+09])

In [49]:
np.sum(valor_de_cartera_colones)/1000000

122768.2176910609

In [50]:
valor_de_cartera_colones_opt = valor_de_cartera_dolares*(tc_dolar_colon['Optimista'][614])
valor_de_cartera_colones_opt

array([2.00340487e+10, 9.01781747e+09, 3.74147941e+10, 1.85532611e+10,
       1.50509748e+10, 1.43861478e+10, 9.51983155e+09])

In [51]:
np.sum(valor_de_cartera_colones_opt)/1000000

123976.87557006796

In [52]:
valor_de_cartera_colones_pes = valor_de_cartera_dolares*(tc_dolar_colon['Pesimista'][614])
valor_de_cartera_colones_pes

array([1.96434225e+10, 8.84198700e+09, 3.66852760e+10, 1.81915075e+10,
       1.47575091e+10, 1.41056450e+10, 9.33421275e+09])

In [53]:
np.sum(valor_de_cartera_colones_pes)/1000000

121559.55981205386

In [90]:
porcentajes_cartera = valor_de_cartera_colones/np.sum(valor_de_cartera_colones)*100
porcentajes_cartera

array([16.15950445,  7.27378991, 30.17884902, 14.96509818, 12.14014687,
       11.60389608,  7.67871549])

### ACP

#### Escenario base

In [55]:
from sklearn.preprocessing import StandardScaler

# Normalizar los datos
scaler = StandardScaler()
rendimientos_normalizados = scaler.fit_transform(rendimientos)

In [56]:
from sklearn.decomposition import PCA

# Configurar el modelo de PCA para extraer todas las componentes
pca = PCA(n_components=len(rendimientos.columns))
componentes_principales = pca.fit_transform(rendimientos_normalizados)
componentes_principales

array([[-1.77207405e+00, -9.66208594e-01, -2.66437661e-01, ...,
         5.57172597e-02,  3.21146960e-02,  2.84584275e-01],
       [-3.16635148e+00,  1.35713233e+00,  8.39461459e-01, ...,
         1.43094676e-01, -7.13400633e-01,  7.17382546e-01],
       [ 2.30221774e+00,  1.14292353e+00, -1.24697101e+00, ...,
         3.11250247e-01, -4.29517711e-01, -1.02322288e-01],
       ...,
       [-4.45503933e-02,  7.47134906e-01,  6.33672366e-01, ...,
         5.23930055e-01, -1.76486984e-01, -1.35338132e-02],
       [ 1.66014264e-01,  3.42396188e-01, -9.59575564e-02, ...,
         6.82771881e-01,  2.99357028e-01, -1.78824590e-01],
       [ 1.54564054e-01, -1.50355232e-01,  7.75789583e-01, ...,
         1.90145570e-03,  9.60955582e-01, -1.37831645e-02]])

In [57]:
covar = np.cov(np.transpose(componentes_principales)) #valores propios de los componentes principales en la diagonal
covar

array([[ 3.10364478e+00,  5.98223266e-16,  3.17043070e-16,
         3.05215952e-17, -7.32518284e-17, -1.61764454e-16,
         3.05215952e-16],
       [ 5.98223266e-16,  1.44178756e+00,  2.25859804e-16,
         3.84572099e-16,  1.92286050e-16,  1.83129571e-17,
        -3.73317261e-16],
       [ 3.17043070e-16,  2.25859804e-16,  7.23990113e-01,
        -5.49388713e-16,  3.05215952e-16, -1.52607976e-17,
         2.51421640e-16],
       [ 3.05215952e-17,  3.84572099e-16, -5.49388713e-16,
         5.92136747e-01, -2.44172761e-17, -2.85376915e-16,
        -5.03606320e-17],
       [-7.32518284e-17,  1.92286050e-16,  3.05215952e-16,
        -2.44172761e-17,  5.39066732e-01,  1.77025252e-16,
        -1.09496223e-16],
       [-1.61764454e-16,  1.83129571e-17, -1.52607976e-17,
        -2.85376915e-16,  1.77025252e-16,  3.50117144e-01,
        -5.29549676e-16],
       [ 3.05215952e-16, -3.73317261e-16,  2.51421640e-16,
        -5.03606320e-17, -1.09496223e-16, -5.29549676e-16,
         2.6128441

In [58]:
sigma = np.sqrt(np.dot(np.dot(np.transpose(valor_de_cartera_colones),covar),valor_de_cartera_colones))
print(sigma)

52385203427.66411


In [59]:
sigma/1000000

52385.203427664106

In [60]:
from scipy.stats import norm

nivel_conf = 0.95
zq = norm.ppf(nivel_conf)
zq

1.6448536269514722

In [61]:
VaR = sigma*zq
VaR

86165991856.584

In [62]:
VaR/1000000

86165.991856584

In [63]:
ES = sigma*np.exp(-(zq**2)/2)/(np.sqrt(2*np.pi)*(1-nivel_conf))
ES

108055630034.12466

In [64]:
ES/1000000

108055.63003412467

#### Escenario pesimista

In [65]:
rendimientos_pes_normalizados = scaler.fit_transform(rendimientos_pes)

In [66]:
pca2 = PCA(n_components=len(rendimientos_pes.columns))
componentes_principales2 = pca2.fit_transform(rendimientos_pes_normalizados)
componentes_principales2

array([[-1.77654453e+00, -9.54979213e-01, -2.50723321e-01, ...,
         5.83700938e-02,  3.19773897e-02,  2.78784018e-01],
       [-3.15157602e+00,  1.35518019e+00,  8.80213576e-01, ...,
         1.56631461e-01, -7.26737413e-01,  6.88999717e-01],
       [ 2.29241515e+00,  1.12763431e+00, -1.26058087e+00, ...,
         3.07009946e-01, -4.34488224e-01, -1.13000339e-01],
       ...,
       [-4.19271835e-02,  7.45320454e-01,  6.57505721e-01, ...,
         5.47129766e-01, -1.86678194e-01, -7.63226661e-03],
       [ 1.59178276e-01,  3.43287890e-01, -8.56579895e-02, ...,
         6.95316138e-01,  2.95681292e-01, -1.63503765e-01],
       [ 1.48516949e-01, -1.44926048e-01,  7.63601375e-01, ...,
         2.87906706e-03,  9.50090605e-01,  2.09836609e-02]])

In [67]:
covar2 = np.cov(np.transpose(componentes_principales2)) #valores propios de los componentes principales en la diagonal
covar2

array([[ 3.12798738e+00,  1.83129571e-16, -5.78384229e-16,
        -6.10431904e-16, -3.17424590e-16, -8.85126260e-17,
        -1.03773424e-16],
       [ 1.83129571e-16,  1.42648745e+00, -3.63206983e-16,
        -2.44172761e-17, -2.13651166e-16, -3.96780737e-17,
        -2.21281565e-17],
       [-5.78384229e-16, -3.63206983e-16,  7.23602945e-01,
         5.58545192e-16,  4.57823928e-17,  1.77025252e-16,
        -2.55809120e-16],
       [-6.10431904e-16, -2.44172761e-17,  5.58545192e-16,
         5.90734223e-01,  2.01442528e-16, -1.61764454e-16,
        -2.79272596e-16],
       [-3.17424590e-16, -2.13651166e-16,  4.57823928e-17,
         2.01442528e-16,  5.34918209e-01, -1.37347178e-16,
        -1.43833017e-16],
       [-8.85126260e-17, -3.96780737e-17,  1.77025252e-16,
        -1.61764454e-16, -1.37347178e-16,  3.45932494e-01,
         1.28190700e-16],
       [-1.03773424e-16, -2.21281565e-17, -2.55809120e-16,
        -2.79272596e-16, -1.43833017e-16,  1.28190700e-16,
         2.6236479

In [68]:
sigma_pes = np.sqrt(np.dot(np.dot(np.transpose(valor_de_cartera_colones_pes),covar2),valor_de_cartera_colones_pes))
print(sigma_pes)

51923129907.59798


In [69]:
sigma_pes/1000000

51923.12990759798

In [70]:
VaR_pes = sigma_pes*zq
VaR_pes

85405948551.185

In [71]:
VaR_pes/1000000

85405.94855118499

In [72]:
ES_pes = sigma_pes*np.exp(-(zq**2)/2)/(np.sqrt(2*np.pi)*(1-nivel_conf))
ES_pes

107102505066.27422

In [73]:
ES_pes/1000000

107102.50506627421

#### Escenario optimista

In [74]:
rendimientos_opt_normalizados = scaler.fit_transform(rendimientos_opt)

In [75]:
pca3 = PCA(n_components=len(rendimientos_opt.columns))
componentes_principales3 = pca3.fit_transform(rendimientos_opt_normalizados)
componentes_principales3

array([[-1.75561369, -0.96757723, -0.27230713, ...,  0.0515405 ,
         0.03374025,  0.28350368],
       [-3.12576463,  1.34320233,  0.8037401 , ...,  0.13230456,
        -0.68392078,  0.72012611],
       [ 2.29034377,  1.13789427, -1.23631302, ...,  0.31434184,
        -0.42511409, -0.09223001],
       ...,
       [-0.03515525,  0.73727166,  0.59552559, ...,  0.50302619,
        -0.15838651, -0.02075505],
       [ 0.17603937,  0.3318072 , -0.1110842 , ...,  0.67213358,
         0.29895568, -0.1861612 ],
       [ 0.15991985, -0.15042107,  0.78378057, ...,  0.00517753,
         0.95148443, -0.03514894]])

In [76]:
covar3 = np.cov(np.transpose(componentes_principales3)) #valores propios de los componentes principales en la diagonal
covar3

array([[ 3.15130736e+00,  5.73805989e-16, -6.33036960e-16,
         6.19588382e-16,  9.76691046e-17, -3.11320271e-16,
        -8.24083070e-17],
       [ 5.73805989e-16,  1.42747584e+00, -1.09877743e-16,
        -9.15647855e-17, -7.01996689e-17, -1.15982062e-16,
         8.49835666e-17],
       [-6.33036960e-16, -1.09877743e-16,  7.17941575e-01,
        -1.34295019e-16,  2.25859804e-16,  2.16703326e-16,
        -7.78300677e-17],
       [ 6.19588382e-16, -9.15647855e-17, -1.34295019e-16,
         5.85949938e-01,  3.54050504e-16, -1.22849421e-16,
        -2.13651166e-17],
       [ 9.76691046e-17, -7.01996689e-17,  2.25859804e-16,
         3.54050504e-16,  5.34571893e-01,  1.95338209e-16,
         2.19373965e-16],
       [-3.11320271e-16, -1.15982062e-16,  2.16703326e-16,
        -1.22849421e-16,  1.95338209e-16,  3.42528557e-01,
         4.62402167e-16],
       [-8.24083070e-17,  8.49835666e-17, -7.78300677e-17,
        -2.13651166e-17,  2.19373965e-16,  4.62402167e-16,
         2.5225233

In [77]:
sigma_opt = np.sqrt(np.dot(np.dot(np.transpose(valor_de_cartera_colones_opt),covar3),valor_de_cartera_colones_opt))
print(sigma_opt)

52938372306.95871


In [78]:
sigma_opt/1000000

52938.37230695871

In [79]:
VaR_opt = sigma_opt*zq
VaR_opt

87075873694.0084

In [80]:
VaR_opt/1000000

87075.8736940084

In [81]:
ES_opt = sigma_opt*np.exp(-(zq**2)/2)/(np.sqrt(2*np.pi)*(1-nivel_conf))
ES_opt

109196658566.16016

In [82]:
ES_opt/1000000

109196.65856616016

### Simulación Histórica

In [83]:
VaRHist = (np.sum(valor_de_cartera_colones)-np.quantile(valor_de_cartera_colones,1-nivel_conf))
VaRHist

113689179484.77191

In [84]:
VaRHist/1000000

113689.17948477191

In [85]:
VaRHist2 = (np.sum(valor_de_cartera_colones_pes)-np.quantile(valor_de_cartera_colones_pes,1-nivel_conf))
VaRHist2

112569905090.09184

In [86]:
VaRHist2/1000000

112569.90509009184

In [87]:
VaRHist3 = (np.sum(valor_de_cartera_colones_opt)-np.quantile(valor_de_cartera_colones_opt,1-nivel_conf))
VaRHist3

114808453879.45203

In [88]:
VaRHist3/1000000

114808.45387945202